version: "3.8"

services:
  db:
    image: postgis/postgis:15-3.4
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/ny_tax.sql:/docker-entrypoint-initdb.d/1-ny_tax.sql

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"

  client:
    build: ./client
    container_name: client
    restart: always
    depends_on:
      - backend
    env_file:
      - ./client/.env
    ports:
      - "4173:4173"

volumes:
  postgres_data:
